baseURL = 'https://josephnewman.github.io/'
languageCode = 'en-us'
title = 'Joseph Newman'
theme = 'Hugo Bear Blog'
[params]
    footerText = '© Joseph Newman 2024'
    favicon = 'images/favicon.png'
    hideMadeWithLine = true